also export AR AS NM and PKGCONFIG variable

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12,12 +12,28 @@ for i in "$@"; do
 			SYSROOT="${i#*=}"
 			shift # past argument=value
 			;;
-		--with-CC=*)
+		--with-CC=*|--cc=*)
 			CC="${i#*=}"
 			shift # past argument=value
 			;;
-		--with-LD=*)
+		--with-LD=*|--ld=*)
 			LD="${i#*=}"
+			shift # past argument=value
+			;;
+		--ar=*)
+			AR="${i#*=}"
+			shift # past argument=value
+			;;
+		--as=*)
+			AS="${i#*=}"
+			shift # past argument=value
+			;;
+		--nm=*)
+			NM="${i#*=}"
+			shift # past argument=value
+			;;
+		--pkgconfig=*)
+			PKGCONFIG="${i#*=}"
 			shift # past argument=value
 			;;
 		--host=*)
@@ -43,7 +59,7 @@ if [ "$HOST" != "" ] ; then
 fi
 
 if [ "$CC" = "" ] ; then
-	if ${PREV}gcc --version > /dev/null ; then
+	if ${PREV}gcc --version > /dev/null 2>/dev/null ; then
 		CC="${PREV}gcc"
 	elif ${PREV}clang --version > /dev/null ; then
 		CC="${PREV}clang"
@@ -54,10 +70,36 @@ if [ "$CC" = "" ] ; then
 fi
 
 if [ "$LD" = "" ]; then
-	if ${PREV}ld --version > /dev/null ; then
+	if ${PREV}ld --version > /dev/null 2>/dev/null ; then
 		LD="${PREV}ld"
 	else
 		echo "error : no linker found"
+		exit 1
+	fi
+fi
+
+if [ "$AS" = "" ]; then
+	if ${PREV}as --version > /dev/null 2>/dev/null ; then
+		AS="${PREV}as"
+	else
+		echo "error : no assembler found"
+		exit 1
+	fi
+fi
+
+if [ "$AR" = "" ]; then
+	if ${PREV}ar --version > /dev/null 2>/dev/null ; then
+		AR="${PREV}ar"
+	else
+		echo "error : no archiver found"
+		exit 1
+	fi
+fi
+if [ "$PKGCONFIG" = "" ]; then
+	if pkg-config --version > /dev/null 2>/dev/null ; then
+		PKGCONFIG="pkg-config"
+	else
+		echo "error : pkg-config not found"
 		exit 1
 	fi
 fi
@@ -72,4 +114,8 @@ echo "HOST=$HOST" >> config.mk
 echo "PREFIX=$PREFIX" >> config.mk
 echo "CC=$CC" >> config.mk
 echo "LD=$LD" >> config.mk
+echo "AS=$AS" >> config.mk
+echo "AR=$AR" >> config.mk
+echo "NM=$NM" >> config.mk
+echo "PKGCONFIG=$PKGCONFIG" >> config.mk
 echo "SYSROOT=$SYSROOT" >> config.mk
